### ISSUE TITLE
RubAbstractTextArea>>keyboardFocusChange: aBoolean   Rectangle maybe create wrong 

### ISSUE THREAD

**Issue by liangbing64** [tomooda/PharoIM#18]
keyboardFocusChange: aBoolean

	aBoolean
		ifTrue: [ 
			self hasFocus: true.
			editing := false.
			self requestTextEditingAt:
				((self cursor positionInWorld corner: self cursor positionInWorld) 
					 translateBy: 0 @ (self font height + 4)) truncated.
----------------------------------------------------------------------------------------
	(self cursor positionInWorld corner: (self cursor positionInWorld 
					 translateBy: 0 @ (self font height + 4))) truncated.
-----------------------------------------------------------------------------------------

			self showOverEditableTextCursor ]
		ifFalse: [ 
			self hasFocus: false.
			self requestStopTextEditing.
			editing = true ifTrue: [ editing := false ].
			self hideOverEditableTextCursor ].
	super keyboardFocusChange: aBoolean

**Comment by tomooda** [comment]
I honestly don't have a good documentation of `SDL_SetTextInputRect()`.
Do you know any documentation that explains what rectangle is expected as the argument?
I know the official document at https://wiki.libsdl.org/SDL_SetTextInputRect , but the argument `rect` is poorly explained.
Your interpretation seems reasonable, and I'd appreciate if you give me a pointer to a better documentation.

**Comment by liangbing64** [comment]
sorry, I know nothing about SDL2.  I mean 
((self cursor positionInWorld corner: self cursor positionInWorld) translateBy: 0 @ (self font height + 4)) truncated.
 the result rectangle's origin and corner are the same point . not a real rectangle。Thank your help on IME.

**Comment by tomooda** [comment]
Okay, I think your code looks good and I will commit it in a few days. Thank you for your contribution! 👍

**Comment by tomooda** [comment]
merged to tomooda/PharoIM:main (https://github.com/tomooda/PharoIM/commit/0c7c25652d304059f5671972cd4e9f69ba0b3944).
PR sent to pharo-project/pharo:Pharo11 (https://github.com/pharo-project/pharo/pull/11474).
Let's hope it'll be merged. 😄

**Comment by tomooda** [comment]
The PR is now merged into Pharo11.
Thank you for improving PharoIM and Pharo, @liangbing64
