### ISSUE TITLE
unexpectedly fixed the first full-width alphanumeric character on Windows + ATOK

### ISSUE THREAD

**Issue by sumim** [tomooda/PharoIM#7]
The first input of a full-width alphanumeric character is unexpectedly fixed. Using ATOK for Ichitaro 2020.
no problem if using Google IM

第一文字目が全角英数記号だと無条件で確定されます。ATOK for 一太郎2020 を使用。
Google入力では問題ありません。

**Comment by tomooda** [comment]
Thank you for reporting this interesting case.
Microsoft IME as well as Google IME looks happy.
I suspect ATOK is sending IM events differently from other IMs.
It would be helpful if you could trace executions of `RubAbstractTextArea>>textEdition:` and `RubAbstractTextArea>>textInput:` when the full-width alphanumeric is typed.

**Comment by sumim** [comment]
Apparently, I was too quick to judge. The characters that I thought were entered as full-width alphanumeric characters were entered as half-width characters. I'm sorry.
